# Dataset
dataset: ImageNet1000
scenario: class
order: 0
init: 500
tasks: 6
# General setting
scheme: SSIL
optim: SGD
lr: 0.1
decay: 1.0e-4
momentum: 0.9
steps: [30, 60]
gamma: 0.1
memory: 20
mcat: True
bs: 128
mbs: 32
epochs: 90
# Hyperparameters
tau: 2
lambd: 4
# Device
mode: DP
gpuid: [0, 1, 2, 3]
workers: 16
pin_memory: True
seed: 1993
# Output
name: ssil/imagenet1000/init500_6tasks
