# Dataset
dataset: CIFAR100
scenario: class
order: 0
init: 50
tasks: 6
# General setting
scheme: SSIL
optim: SGD
lr: 0.1
decay: 5.0e-4
momentum: 0.9
steps: [80, 120]
gamma: 0.1
memory: 20
mcat: True
bs: 128
mbs: 32
epochs: 160
# Hyperparameters
tau: 2
lambd: 4
# Device
mode: GPU
gpuid: 0
workers: 4
seed: 1993
# Output
name: ssil/cifar100/init50_6tasks
