# Dataset
dataset: CIFAR10
scenario: class
init: 0
tasks: 5
# General setting
scheme: FineTune
optim: SGD
lr: 0.00003
decay: 5.0e-4
momentum: 0.9
steps: [80, 120]
gamma: 0.1
bs: 128
epochs: 10
# Device
mode: GPU
gpuid: 0
workers: 4
seed: 1993
# Output
name: finetune/cifar10/init2_5tasks
