# Dataset
dataset: ImageNet100
scenario: class
order: 0
init: 50
tasks: 6
# General setting
scheme: LwF
optim: SGD
lr: 0.1
decay: 1.0e-4
momentum: 0.9
steps: [30, 60]
gamma: 0.1
bs: 128
epochs: 90
# Hyperparameters
tau: 2
# Device
mode: GPU
gpuid: 0
workers: 16
seed: 1993
# Output
name: lwf/imagenet100/init50_6tasks
