# Dataset
dataset: ImageNet1000
scenario: class
order: 0
init: 500
tasks: 6
# General setting
scheme: iCaRL
optim: SGD
lr: 0.1
decay: 1.0e-4
momentum: 0.9
steps: [30, 60]
gamma: 0.1
memory: 20
bs: 128
epochs: 90
# Hyperparameters
tau: 2
# Device
mode: DP
gpuid: [0, 1, 2, 3]
workers: 16
pin_memory: True
seed: 1993
# Output
name: icarl/imagenet1000/init500_6tasks
