# Dataset
dataset: ImageNet1000
scenario: class
order: 0
init: 500
tasks: 26

# General setting
scheme: MTD
base: AFC
model: scheme.replay.podnet.basenet.BasicNet
convnet: resnet18_importance
convnet_config:
  nf: 64
optim: SGD
lr: 0.10
decay: 0.0001
momentum: 0.9
scheduling: cosine
gamma: 0.1
memory: 20
bs: 128
epochs: 90

# Hyperparameters
classifier_config:
  type: cosine
  proxy_per_class: 10
  distance: neg_stable_cosine_distance

postprocessor_config:
  type: learned_scaling
  initial_value: 1.0

pod_flat:
  scheduled_factor: 10.0

feature_distil:
  scheduled_factor: 10.0
  collapse_channels: pixel

nca:
  margin: 0.6
  scale: 1.
  exclude_pos_denominator: true

groupwise_factors:
  old_weights: 0.

finetuning_config:
  lr: 0.02
  blr: 0.001  # learning rate for branch
  epochs: 20

weight_generation:
  type: imprinted
  multi_class_diff: kmeans

mtd:
  num: 1
  tau: 2
  lambd: 1000
  noise: 0.03
  dissimilar: 1.0
  permute: true  #true, false
  scale: false
  kl:
    p: 1000
    c: 1000
  output: average  # average, origin, max
  stages: ['layer3', 'layer4']  # ['layer3', 'layer4']
#  dis_emb_avg: true
#  mixup:
#    a: 0.1
#    b: 1

# Device
mode: DP
gpuid: [0, 1, 2, 3]
workers: 16
FAST: True
threads: 32
pin_memory: True
seed: 1993
# Output
name: mtd/afc/imagenet1000/init500_26tasks
