# Dataset
dataset: FIVE
datafun: scheme.regularization.gpm.dataset.five.FIVE
pc_valid: 0.05  # fraction of training data used for validation
scenario: task
tasks: 5
# General setting
scheme: GPM
optim: SGD
lr: 0.1
lr_min: 1.0e-3
lr_patience: 5
decay: 0.
momentum: 0.9
gamma: 0.3333333
bs: 64
epochs: 100

model: scheme.regularization.gpm.model.ResNet18
nf: 20

GPM:
  th: [0.965, 0.965, 0.965, 0.965, 0.965, 0.965, 0.965, 0.965, 0.965, 0.965,
       0.965, 0.965, 0.965, 0.965, 0.965, 0.965, 0.965, 0.965, 0.965, 0.965]

# Device
mode: GPU
gpuid: 0
seed: 1
# Output
name: gpm/five/TIL_5tasks
