# Dataset
dataset: CIFAR100
scenario: class
order: 0
init: 50
tasks: 6
# General setting
scheme: MTD
base: SSIL
optim: SGD
lr: 0.1
decay: 5.0e-4
momentum: 0.9
steps: [80, 120]
gamma: 0.1
memory: 20
mcat: True
bs: 128
mbs: 32
epochs: 160
# Hyperparameters
tau: 2

finetune:
  blr: 0.01
  epochs: 20
  steps: [10]
  gamma: 0.1

mtd:
  num: 1
  tau: 2
  lambd: 4
  noise: 0.03
  dissimilar: 1.0
  permute: true  #true, false
  scale: false
  kl:
    p: 4
    c: 4
  output: average  # average, origin, max
  stages: ['stage_3', 'stage_4']
#  dis_emb_avg: true

# Device
mode: GPU
gpuid: 0
workers: 4
seed: 1993
# Output
name: mtd/ssil/cifar100/init50_6tasks
